name: Deploy Content to laworkspacetest [10c6499f-58e0-4775-9e92-9c3d85f58310]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-10c6499f-58e0-4775-9e92-9c3d85f58310.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-10c6499f-58e0-4775-9e92-9c3d85f58310.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'vc-test-rg'
      workspaceName: 'laworkspacetest'
      workspaceId: '962bd4a7-d2c6-44af-8c4e-4a3b5d8f8f50'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'Playbook'
      branch: 'master'
      sourceControlId: '10c6499f-58e0-4775-9e92-9c3d85f58310'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_10c6499f58e047759e929c3d85f58310 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_10c6499f58e047759e929c3d85f58310 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_10c6499f58e047759e929c3d85f58310 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_10c6499f58e047759e929c3d85f58310 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_10c6499f58e047759e929c3d85f58310 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_10c6499f58e047759e929c3d85f58310 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_10c6499f58e047759e929c3d85f58310 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_10c6499f58e047759e929c3d85f58310 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_10c6499f58e047759e929c3d85f58310 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-10c6499f-58e0-4775-9e92-9c3d85f58310.ps1